# Generated by Django 4.0.3 on 2022-05-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginDetail', '0002_alter_logindetail_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetail',
            name='email',
            field=models.EmailField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='logindetail',
            name='imageUrl',
            field=models.URLField(max_length=500),
        ),
    ]
