# Generated by Django 4.0.3 on 2022-03-22 04:38

import GovtJobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovtJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to=GovtJobs.models.GovtJobs)),
                ('job_title', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=15)),
                ('age_limit', models.CharField(max_length=30)),
                ('vacancy', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('read_more', models.URLField(max_length=100)),
                ('apply', models.URLField()),
                ('search', models.CharField(max_length=50)),
            ],
        ),
    ]
