# Generated by Django 4.0.3 on 2022-04-10 03:38

import GovtJobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovtJobs', '0018_alter_govtjobs_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govtjobs',
            name='logo',
            field=models.ImageField(upload_to=GovtJobs.models.GovtJobs),
        ),
        migrations.AlterField(
            model_name='govtjobs',
            name='search',
            field=models.CharField(max_length=150),
        ),
    ]
