# Generated by Django 4.1.2 on 2022-10-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovtJobs', '0027_alter_govtjobs_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govtjobs',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='govtjobs',
            name='qualification',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='govtjobs',
            name='read_more',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='govtjobs',
            name='search',
            field=models.CharField(max_length=200),
        ),
    ]
