# Generated by Django 4.0.3 on 2022-03-25 09:18

import PrivateJobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to=PrivateJobs.models.PrivateJobs)),
                ('job_title', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=15)),
                ('experience', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('read_more', models.URLField(max_length=100)),
                ('apply', models.URLField()),
                ('search', models.CharField(max_length=50)),
            ],
        ),
    ]
