# Generated by Django 4.0.3 on 2022-03-25 09:23

import PrivateJobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivateJobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatejobs',
            name='last_date',
            field=models.DateField(default='2022-03-22'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='logo',
            field=models.ImageField(upload_to=PrivateJobs.models.PrivateJobs),
        ),
    ]
