# Generated by Django 4.0.3 on 2022-04-10 03:38

import PrivateJobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivateJobs', '0002_privatejobs_last_date_alter_privatejobs_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatejobs',
            name='logo',
            field=models.ImageField(upload_to=PrivateJobs.models.PrivateJobs),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='search',
            field=models.CharField(max_length=150),
        ),
    ]
