# Generated by Django 4.1.2 on 2022-10-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivateJobs', '0014_alter_privatejobs_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatejobs',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
