# Generated by Django 4.1.2 on 2022-10-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivateJobs', '0015_alter_privatejobs_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatejobs',
            name='experience',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='qualification',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='salary',
            field=models.CharField(max_length=100),
        ),
    ]
