# Generated by Django 4.0.3 on 2022-05-21 08:23

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to=Blog.models.Blog)),
                ('blog', models.TextField()),
            ],
        ),
    ]
